### ISSUE TITLE
Port for stm32f4 variants?

### ISSUE THREAD

**Issue by SgoSkz** [Nitrokey/chopstx#3]
Will there be a port for stm32f4 black pill boards? I have a couple laying around and I would like to try this out. If there are ways I can help, I would be glad to find out where to start.

**Comment by szszszsz** [comment]
Hi!
We do not plan any, instead investing time into Rust-based firmware. You can try asking upstream at:
- https://salsa.debian.org/gnuk-team/chopstx/chopstx

I expect STM32F4 would work with just a small modifications from STM32L4 or STM32F1.
